### ISSUE TITLE
有无必要关闭 CoreOS 自动升级

### ISSUE THREAD

**Issue by pineking** [k8sp/k8s-tensorflow#11]
在[编译 CoreOS Nvida GPU 驱动](https://github.com/Clarifai/coreos-nvidia)时，需要指定 CoreOS的 version 和 channel

如果开启 CoreOS 自动升级， 会存在 CoreOS version 和之前编译的 Nvidia GPU 驱动不一致的情况

另外一种解决方案，是设置一个定时 cron 任务， https://github.com/Clarifai/coreos-nvidia#automating-driver-builds-for-new-os-releases 自动构建 latest CoreOS 版本的驱动

**Comment by jiamliang** [comment]
同样的，k8s 需要自动更新版本吗？还有其他的。

**Comment by pineking** [comment]
@jiamliang k8s 不需要，我们需要确认下 k8s 都加了哪些 features， 再决定要不要升级。

**Comment by pineking** [comment]
CoreOS 考虑 GPU 应该关闭自动升级
