### ISSUE TITLE
编译 CoreOS Nvidia 驱动对比

### ISSUE THREAD

**Issue by pineking** [k8sp/k8s-tensorflow#13]
编译方法：
- 方法 A：https://github.com/emergingstack/es-dev-stack
- 方法 B：https://github.com/k8sp/k8s-tensorflow/pull/14  此方法编译方便，推荐 (参考自 https://github.com/Clarifai/coreos-nvidia )

| 方案 | CoreOS Version | Nvidia driver 352.39 | Nvidia driver 367.35 |
| --- | --- | --- | --- |
| 方法 A | 1010.5.0(4.5.0-coreos-rc1) | 工作正常 | 编译通过，不能正常工作（undefined in Nvidia-uvm） |
| 方法 A | 1068.9.0(4.6.3-coreos) | 编译不通过 https://github.com/k8sp/k8s-tensorflow/issues/12 | 未尝试 |
| 方法 B | 1010.5.0(4.5.0-coreos-rc1) | 需要修改，打补丁 nvprocfs.patch | 编译通过，不能正常工作（undefined in Nvidia-uvm） |
| 方法 B | 1068.9.0(4.6.3-coreos) | 编译不通过 https://github.com/k8sp/k8s-tensorflow/issues/12 | 工作正常 |

注：
- 方法 B 是在CentOS 7.2.1511 测试， systemd-nspawn 版本为 219，比 https://github.com/Clarifai/coreos-nvidia  建议的版本 229 低
- 方法 B 只给出了编译 Nvidia driver，后续操作需参考方法 A
- 方法 B 简单方便，优于方法 A，推荐

**结论：**

**采用 方法B 编译 + 1068.9.0(4.6.3-coreos) + Nvidia driver 367.35**

**运行应用程序只需加载已编译好的驱动，不需要再重新编译**

**Comment by vienlee** [comment]
对于已 insmod 过的模块测试
经过测试:
1. 重启机器需要重新 insmod nvidia.ko, nvidia-uvm.ko
2. 已经加入的模块文件, 移除, 不会影响正运行
3. 通过以上两条验证, 重启需要重新插入模块
