### ISSUE TITLE
8月10日进展汇总与下一步计划

### ISSUE THREAD

**Issue by pineking** [k8sp/k8s-tensorflow#2]
工作与现有结论：
工作：
- 青松：在两台物理机同时以kernel方式挂载同一块RBD，验证同时读写的实验https://github.com/k8sp/ceph-rbd/issues/2
  启动MDS，验证ceph FS 功能，并以kernel 方式挂载 ceph FS。
- 文山: 和兴帅一起研究在 k8s 上跑通 tensorflow. [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/dist_test](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/dist_test)
- 家盟
- 兴帅：测试应用程序访问数据。基于[librados](http://docs.ceph.com/docs/master/rados/api/librados-intro/)和[librbd](http://docs.ceph.com/docs/master/rbd/librbdpy/#librbd-python)访问Ceph，可以存储对象数据，但存储文件的操作不成功。经测试后，使用[RADOS](http://docs.ceph.com/docs/firefly/man/8/rados/)命令可以存储文件。

结论：
- 应用程序基于librados 访问Ceph，底层访问，直接存储对象数据不直观，和现有文件系统基于文件夹和文件的逻辑差别大，所以这个尝试可以暂停。
- RBD 存在不能多docker 同时挂载写的问题，而且多docker 同步存在时间问题， RBD本身也比较零碎。
- docker 启动mds ，ceph FS 目前可以正常work。

下一步计划：
- k8s下的tensorflow分布式调用 （优先级高）
- cephfs 分目录挂载与权限控制（kernel vs. fuse）（优先级高）
- 定制挂载好ceph的tensorflow image （优先级高）
- 基于GPU 的 k8s 集群 （优先级中）
- k8s下访问 cephfs 作为存储 （优先级中）
- k8s 自动调度ceph pods，增强ceph pods稳定性 （优先级低）

**Comment by pineking** [comment]
任务分工：
- k8s下的tensorflow分布式调用 （优先级高）---文山，兴帅
- cephfs 分目录挂载与权限控制（kernel vs. fuse）（优先级高）---家盟
- 定制挂载好ceph的tensorflow image （优先级高）---青松

**Comment by wangkuiyi** [comment]
FYI:

> The basic idea is that the master, each worker, and each parameter server runs in a separate Kubernetes replication controller of size 1. Kubernetes gives stable names to each of these processes, which you can use to build a tf.train.ClusterSpec, and interconnect the different processes.
1. [Running Distributed Tensorflow in Kubernetes](https://github.com/amygdala/tensorflow-workshop/blob/master/workshop_sections/distributed_tensorflow/README.md)
2. [Diving into machine learning
   through TensorFlow](https://storage.googleapis.com/amy-jo/talks/tf-workshop.pdf) Page 79.
