### ISSUE TITLE
利用Harbor建private registry

### ISSUE THREAD

**Issue by sunxs1101** [k8sp/k8s-tensorflow#20]
先写下，还未完成

Harbor是VMware开源的企业级Docker Registry服务，以Docker registry镜像为基础，提供Web UI，User management & access control, Audit logs等功能。Harbor可以通过Docker-compose部署，可以离线部署，下面介绍Docker-compose方法部署
## 通过Docker-compose部署Harbor

在10.10.10.202上部署Harbor
1. 获取源码 $ git clone https://github.com/vmware/harbor
2. 编辑配置文件Deploy/harbor.cfg，配置hostname, admin密码和邮箱等信息
3. 通过下面的指令安装Harbor

```
 $ cd Deploy
 $ ./prepare
 $ docker-compose up -d
```

.prepare是python文件，执行上述指令前需要安装python, docker和docker compose。参考[docker compose官方文档](https://docs.docker.com/compose/install/)安装docker compose

```
$ curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
$ chmod +x /usr/local/bin/docker-compose
$ docker-compose --version
```

在202上建立Dockerfile文件，如下

```
FROM python
RUN git clone https://github.com/vmware/harbor
WORKDIR harbor/Deploy
RUN ./prepare
RUN curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
RUN docker-compose up -d
```

执行docker build -t harbor . 建立镜像，出现下面的问题

```
Step 6 : RUN chmod +x /usr/local/bin/docker-compose
 ---> Using cache
 ---> 03c3957768fe
Step 7 : RUN docker-compose up -d
 ---> Running in bf5e3bd5594a
Couldn't connect to Docker daemon. You might need to install Docker:

https://docs.docker.com/engine/installation/
The command '/bin/sh -c docker-compose up -d' returned a non-zero code: 1
```

在Dockerfile中添加FROM ubuntu，FROM docker，运行仍旧有问题。编写Dockerfile时，Dockerfile中可以用多个FROM创建多个镜像，但这个Dockerfile创建的容器，只有最后一个FROM起作用。
参考才云科技ppt，在k8s集群中运行harbor。
## k8s集群中运行Harbor
- Step 1:容器化配置文件

cp /home/core/harbor/harbor/Deploy/kubernetes/dockerfiles/registry-dockerfile /home/core/harbor/harbor/Deploy/Dockerfile Dockerfile文件中内容如下：

```
FROM library/registry:2.3.0
ADD ./config/registry/ /etc/registry/
ADD ./kubernetes/dockerfiles/registry-config.yml /etc/registry/config.yml
CMD ["/etc/registry/config.yml"]
```

建立镜像 docker build -t="harbork8s" . 后面的还未完成
- Step 2:动态配置文件
  - 内部服务地址 -> DNS
  - Registry地址
  - Registry地址为Kubernetes中的地址
  - Kubernetes会动态生成IP

在./kubernetes/ui-rc.yaml中配置
- Step 3: 配置Registry地址
  - 使用rolling-update
  - 先不设置IP，等IP产生好了之后再编译镜像
  - 使用rolling-update更新镜像

在./kubernetes/dockerfiles/registry-config.yml中配置
- Step 4: 支持HTTPS协议
## registry测试

安装完harbor之后，可以打开浏览器 http://reg.yourdomain.com ，创建myproject，然后可以login，push镜像。

```
$ docker login reg.yourdomain.com
$ docker push reg.yourdomain.com/myproject/myrepo:mytag
```
### 参考
- https://github.com/vmware/harbor
- https://docs.docker.com/compose/install/

**Comment by wangkuiyi** [comment]
为什么不用Docker registry，而要用Harbor？
