### ISSUE TITLE
k8s 调度 GPU

### ISSUE THREAD

**Issue by pineking** [k8sp/k8s-tensorflow#7]
- http://blog.clarifai.com/how-to-simplify-building-nvidia-gpu-drivers-on-coreos
- http://blog.clarifai.com/how-to-scale-your-gpu-cloud-infrastructure-with-kubernetes

**Comment by wangkuiyi** [comment]
看上去clarifai这家公司一方面向Kubernetes贡献了源码，一方面借此机会要做一些商业运营。我们应该仔细看看，clarifai具体想做什么。

**Comment by wangkuiyi** [comment]
仔细阅读了 @pineking 贴的两个链接。都很受启发：
1. http://blog.clarifai.com/how-to-simplify-building-nvidia-gpu-drivers-on-coreos
   
   我之前在Docker Container里build和执行nvidia driver，用的是这个[办法](https://github.com/emergingstack/es-dev-stack)。但是它引入了一些对CoreOS的假设条件。在其中的[一个issue里](https://github.com/emergingstack/es-dev-stack/issues/8)，大家讨论了用CoreOS为开发者提供的一个development Docker image来build，就可以不需要这些假设条件了。而 @pineking  贴的[这个方法](http://blog.clarifai.com/how-to-simplify-building-nvidia-gpu-drivers-on-coreos)对应的[Github repo](https://github.com/Clarifai/coreos-nvidia/blob/master/build.sh#L12)就用的是CoreOS的development container。
2. http://blog.clarifai.com/how-to-scale-your-gpu-cloud-infrastructure-with-kubernetes
   
   描述用 1. 中描述的方法，在Kubernetes on CoreOS机群里跑Tensorflow jobs。

**Comment by pineking** [comment]
@wangkuiyi https://developer.clarifai.com/
我上午理解错了，这家是卖图像和视频识别 API 的。

**Comment by wangkuiyi** [comment]
@pineking 明白了
