### ISSUE TITLE
创建私有 docker registry 存储内部 images

### ISSUE THREAD

**Issue by pineking** [k8sp/k8s-tensorflow#9]
方便下载

https://docs.docker.com/registry/deploying/
https://github.com/docker/distribution/blob/master/docs/deploying.md

推荐 
1. 关于如何运行 Docker registry：https://github.com/vmware/harbor
2. 一个更基本的关于运行 Docker registry 的连接： https://docs.docker.com/registry/
3. http://www.jianshu.com/p/141855241f2d

**Comment by wangkuiyi** [comment]
澄清一下：我们在 auto-install repo 里的讨论中，讨论了两个 docker registry：
1. 运行在 bootstrapper server 上，用来提供Kubernetes本身需要的images。
2. 运行在Kubernetes机群上，用来提供在Kubernetes机群上跑的各种应用（比如Tensorflow）的images。

和 @pineking 确认，这里说的是 2. 。

**Comment by sunxs1101** [comment]
kubernetes中私有registry https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry
官方issue https://github.com/kubernetes/kubernetes/issues/19033

**Comment by sunxs1101** [comment]
建domain registry
 - 在/etc/ssl/openssl.cnf中的v3_ca部分添加subjectAltName = IP:10.10.10.201
 - 生成TLS证书：mkdir -p certs && openssl req -newkey rsa:4096 -nodes -sha256 -keyout certs/domain.key -x509 -days 365 -out certs/domain.crt
 - cp domain.crt /etc/docker/certs.d/10.10.10.201:5000/ca.crt

**Comment by sunxs1101** [comment]
# 创建私有domain registry

将10.10.10.202作为domain registry server，设置domain registry名为10.10.10.202，创建过程如下
-  在/etc/ssl/openssl.cnf中的v3_ca部分添加subjectAltName = IP:10.10.10.202

```
[ v3_ca ]
subjectAltName = IP:10.10.10.202
```
- 生成TLS证书

为了让registry被集群中其他机器可用，Docker engine需要用TLS来认证，证书生成操作如下

```
mkdir -p certs && openssl req -newkey rsa:4096 -nodes -sha256 -keyout certs/domain.key -x509 -days 365 -out certs/domain.crt  
```

此过程中会提示有一些选项需要自定义输入
- 让每个docker daemon信赖证书

```
mkdir /etc/docker/certs.d/10.10.10.202:5000
cp domain.crt /etc/docker/certs.d/10.10.10.202:5000/ca.crt 
```

Registry在/etc/docker/certs.d/10.10.10.202:5000/路径查找TLS证书
- 重启engine deamon:  `systemctl restart docker`
- 启动registry:2

```
docker run -d -p 5000:5000 --restart=always --name registry \
  -v `pwd`/certs:/certs \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  registry:2
```
- 测试registry

```
docker pull ubuntu
docker tag ubuntu 10.10.10.201:5000/ubuntu
docker push 10.10.10.201:5000/ubuntu

core@00-25-90-c0-f6-ee ~/certs $ docker push 10.10.10.201:5000/ubuntu
The push refers to a repository [10.10.10.201:5000/ubuntu]
unable to ping registry endpoint https://10.10.10.201:5000/v0/
v2 ping attempt failed with error: Get https://10.10.10.201:5000/v2/: dial tcp 10.10.10.201:5000: getsockopt: connection refused
 v1 ping attempt failed with error: Get https://10.10.10.201:5000/v1/_ping: dial tcp 10.10.10.201:5000: getsockopt: connection refused
```

这样的registry是不安全的，需要添加认证
- 为Registry添加认证

为了限制其他用户对registry的访问，增加registry的安全性，需要为registry添加认证，操作如下

```
mkdir auth
docker run --entrypoint htpasswd registry:2 -Bbn testuser testpassword > auth/htpasswd
```

用户名设置为testuser，密码设置为testpassword，这两个都可以自己设定。关闭前面步骤中的registry，按下面操作重新启动registry

```
docker run -d -p 5000:5000 --restart=always --name registry \
  -v `pwd`/auth:/auth \
  -e "REGISTRY_AUTH=htpasswd" \
  -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
  -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
  -v `pwd`/certs:/certs \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  registry:2
```
- 本机对domain registry的访问测试

在202上登录domain registry名为10.10.10.202的Registry，需要输入registry认证的用户名密码和生成TLS时设置的邮箱。登录后push镜像，如下

```
docker login 10.10.10.202:5000
docker tag ubuntu 10.10.10.202:5000/ubuntu
docker push 10.10.10.202:5000/ubuntu
```
- 集群中其他机器对domain registry的访问测试

首先从202机器上的拷贝domain.crt到集群中某机器的相应路径

```
cp domain.crt /etc/docker/certs.d/10.10.10.202:5000/ca.crt
```

然后登录Registry进行push/pull操作

```
docker login 10.10.10.202:5000
docker push 10.10.10.202:5000/ubuntu
```

本例中domain registry名是registry server的IP，如果domain registry名不是registry server的IP，需要在/etc/hosts中添加registry server的IP与主机名，将IP映射到domain registry名。

```
vi /etc/hosts
添加10.10.10.202 myregistrydomain.com
```

### 参考
- https://docs.docker.com/registry/deploying/#/let-s-encrypt
- https://docs.docker.com/registry/insecure/

**Comment by wangkuiyi** [comment]
https://github.com/k8sp/auto-install/pull/128
